name: ndd_analysis

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.11
  - numpy=2.2.4
  - scipy=1.15.2
  - pandas=2.2.3
  - matplotlib-base=3.10.1
  - seaborn=0.13.2
  - statsmodels=0.14.4
  - gseapy=1.1.6
  - pyyaml=6.0.2
  - requests
  - certifi
  - packaging
  - openpyxl          # often useful with pandas
  - pip
